
function picsModal($scope) {
    $scope.imagelists = [{
        categroyid: 1,
        categroyname: "未分组",
        picsize: 6,
        pics: [{
            id: 1,
            src: "images/Fans/head1.jpg",
            name: "images1"
        }, {
            id: 2,
            src: "images/Fans/head2.jpg",
            name: "images1"
        }, {
            id: 5,
            src: "images/Fans/head5.jpg",
            name: "images1"
        }, {
            id: 6,
            src: "images/Fans/head6.jpg",
            name: "images1"
        }, {
            id: 7,
            src: "images/Fans/head7.jpg",
            name: "images1"
        }, {
            id: 8,
            src: "images/Fans/head8.jpg",
            name: "images1"
        }, {
            id: 1,
            src: "images/Fans/head1.jpg",
            name: "images1"
        }, {
            id: 2,
            src: "images/Fans/head2.jpg",
            name: "images1"
        }, {
            id: 5,
            src: "images/Fans/head5.jpg",
            name: "images1"
        }, {
            id: 6,
            src: "images/Fans/head6.jpg",
            name: "images1"
        }, {
            id: 7,
            src: "images/Fans/head7.jpg",
            name: "images1"
        }, {
            id: 8,
            src: "images/Fans/head8.jpg",
            name: "images1"
        }, {
            id: 1,
            src: "images/Fans/head1.jpg",
            name: "images1"
        }, {
            id: 2,
            src: "images/Fans/head2.jpg",
            name: "images1"
        }, {
            id: 5,
            src: "images/Fans/head5.jpg",
            name: "images1"
        }, {
            id: 6,
            src: "images/Fans/head6.jpg",
            name: "images1"
        }, {
            id: 7,
            src: "images/Fans/head7.jpg",
            name: "images1"
        }, {
            id: 8,
            src: "images/Fans/head8.jpg",
            name: "images1"
        }]
    }, {
        categroyid: 2,
        categroyname: "分组A",
        picsize: 8,
        pics: [{
            id: 1,
            src: "images/Fans/head1.jpg",
            name: "images1"
        }, {
            id: 8,
            src: "images/Fans/head8.jpg",
            name: "images1"
        }, {
            id: 2,
            src: "images/Fans/head2.jpg",
            name: "images1"
        }, {
            id: 5,
            src: "images/Fans/head5.jpg",
            name: "images1"
        }, {
            id: 6,
            src: "images/Fans/head6.jpg",
            name: "images1"
        }, {
            id: 7,
            src: "images/Fans/head7.jpg",
            name: "images1"
        }, {
            id: 3,
            src: "images/Fans/head3.jpg",
            name: "images1"
        }, {
            id: 4,
            src: "images/Fans/head4.jpg",
            name: "images1"
        }]
    }, {
        categroyid: 3,
        categroyname: "分组A",
        picsize: 4,
        pics: [{
            id: 5,
            src: "images/Fans/head5.jpg",
            name: "images1"
        }, {
            id: 6,
            src: "images/Fans/head6.jpg",
            name: "images1"
        }, {
            id: 7,
            src: "images/Fans/head7.jpg",
            name: "images1"
        }, {
            id: 8,
            src: "images/Fans/head8.jpg",
            name: "images1"
        }]
    }];
}